fix GLI usage breaking faraday >= 2.7.0
slack-ruby/slack-ruby-client pull request #434
Opened 2022-11-27 23:49 UTC by blowfishpro

when using include at the top level, the module gets included in the Object class

`Faraday::Middleware` checks whether it responds to `on_error`, which then finds GLI's `on_error`, which has a different signature and meaning

this resolves that by wrapping the entire CLI in a class so that `GLI::App` is not included in `Object`

we also use GLI's built-in `commands_from` method to avoid having to reference every command file individually

Resolves #433

2022-11-27 23:59 UTC, dblock requested changes
These files *are* auto-generated to keep up with the API, so you want to modify the .erb template and re-generate them, not delete the template. You can do a 1-time update separately so that we can have something clean for this PR, let's start there?

2022-11-28 18:44 UTC, blowfishpro commented
That's what I did, I just did it while the code to update the submodule was commented out.

What documentation updates are required when new API features are pulled in?  I don't really understand the scope of changes that come with updating the submodule.

2022-11-28 21:21 UTC, dblock requested changes
Looks good! Danger is about to complain re:CHANGELOG format, could you please fix and I'll merge?

2022-11-28 21:21 UTC, dblock commented on CHANGELOG.md
> +* [#434](https://github.com/slack-ruby/slack-ruby-client/pull/434): Fix incompatibility with Faraday >= 2.7.0 and GLI usage in the `slack` script [@blowfishpro](https://github.com/blowfishpro)
This needs to match the format of other entries, it's missing a `- before your github account, and a period at the end.

2022-11-28 21:22 UTC, dblock commented
> What documentation updates are required when new API features are pulled in? I don't really understand the scope of changes that come with updating the submodule.

Only CHANGELOG. You can leave that alone for now.

2022-11-29 03:17 UTC, blowfishpro commented
Fixed!

2022-11-29 12:39 UTC, merged

2022-11-29 12:47 UTC, dblock commented
FYI I decided to rename `CLI` to `Cli` in https://github.com/slack-ruby/slack-ruby-client/pull/435. LMK if you think it's a bad idea.

2022-11-30 00:52 UTC, blowfishpro commented
I'm pretty indifferent on that particular point as long as it's consistent.