Support basic Markdown formatting
slack-ruby/slack-ruby-client pull request #520
Opened 2024-07-05 08:45 UTC by nbgoodall

This PR adds basic support for Slack's markdown formatting, specifically **bold**, ~~strikethrough~~ and [links](https://example.com). Non-supported features like headings and tables are left as-is.

Closes #249.

2024-07-05 22:37 UTC, dblock requested changes
Question: are we going to run into situations where the order of these replacements will matter? Like `**bold_italic_**bold` - meaning I wonder whether it’s worth implementing something that actually reads tokens sequentially.

Either way I’m good with a first cut like this. Nitpicks follow.

2024-07-05 22:37 UTC, dblock commented on lib/slack/messages/formatting.rb
> +        end
Let’s chain them as `text.gsub…gsub…` to avoid the temporary variable.

2024-07-06 08:35 UTC, nbgoodall commented
> Question: are we going to run into situations where the order of these replacements will matter? Like `**bold_italic_**bold` - meaning I wonder whether it’s worth implementing something that actually reads tokens sequentially.

@dblock I won't say never, although I haven't found any glaring cases. It wouldn't have converted `*italic*`, which I've now fixed (also accounting for `***bold and italic***` to `*_bold and italic_*`). If other issues come up I'll happily address them, and I've added another spec for nested formatting.

2024-07-07 00:24 UTC, dblock approved these changes

2024-07-07 00:24 UTC, merged

2024-07-07 00:24 UTC, dblock commented
Merged, thank you!