Exclude spec files from gem package
slack-ruby/slack-ruby-client pull request #525
Opened 2024-08-02 08:21 UTC by amatsuda

Here's a patch that excludes files under spec directory from the gem package.

With this patch, the gem package size shrinks as follows:
```
before: 355840 bytes
after:  293376 bytes
```

2024-08-02 19:48 UTC, dblock requested changes
Looks good, see below.

2024-08-02 19:48 UTC, dblock commented on CHANGELOG.md
> -* Your contribution here.
Put this back please.

2024-08-02 22:02 UTC, amatsuda commented on CHANGELOG.md
> -* Your contribution here.
Oops, sorry. Fixed!

2024-08-03 13:03 UTC, dblock approved these changes

2024-08-03 13:03 UTC, merged